Numpy를 이용하여 Convolution 2D 연산을 구현하시오.

In [2]:
import numpy as np

In [53]:
X = np.array([
                [ 
                 [[1, 2, 9, 2, 7], 
                  [5, 0, 3, 1, 8],                                    
                  [4, 1, 3, 0, 6], 
                  [2, 5, 2, 9, 5], 
                  [6, 5, 1, 3, 2]], 
                 [[4, 5, 7, 0, 8], 
                  [5, 8, 5, 3, 5], 
                  [4, 2, 1, 6, 5], 
                  [7, 3, 2, 1, 0], 
                  [6, 1, 2, 2, 6]], 
                 [[3, 7, 4, 5, 0], 
                  [5, 4, 6, 8, 9], 
                  [6, 1, 9, 1, 6], 
                  [9, 3, 0, 2, 4], 
                  [1, 2, 5, 5, 2]] 
                 ], 
                [ 
                 [[7, 2, 1, 4, 2], 
                  [5, 4, 6, 5, 0], 
                  [1, 2, 4, 2, 8], 
                  [5, 9, 0, 5, 1], 
                  [7, 6, 2, 4, 6]], 
                 [[5, 4, 2, 5, 7], 
                  [6, 1, 4, 0, 5], 
                  [8, 9, 4, 7, 6], 
                  [4, 5, 5, 6, 7], 
                  [1, 2, 7, 4, 1]], 
                 [[7, 4, 8, 9, 7], 
                  [5, 5, 8, 1, 4], 
                  [3, 2, 2, 5, 2], 
                  [1, 0, 3, 7, 6], 
                  [4, 5, 4, 5, 5]] 
                 ] 
                ]) 
print('Images:', X.shape)

Images: (2, 3, 5, 5)


In [54]:
filters = np.array([
                      [ 
                       [[1, 0, 1], 
                        [0, 1, 0], 
                        [1, 0, 1]], 
                       [[3, 1, 3], 
                        [1, 3, 1], 
                        [3, 1, 3]], 
                       [[1, 2, 1], 
                        [2, 2, 2], 
                        [1, 2, 1]] 
                       ],
                      [ 
                       [[5, 1, 5], 
                        [2, 1, 2], 
                        [5, 1, 5]], 
                       [[1, 1, 1], 
                        [1, 1, 1], 
                        [1, 1, 1]], 
                       [[2, 0, 2], 
                        [0, 2, 0], 
                        [2, 0, 2]], 
                       ], 
                      [ 
                       [[5, 1, 5], 
                        [2, 1, 2], 
                        [5, 1, 5]],
                       [[1, 1, 1], 
                        [1, 1, 1], 
                        [1, 1, 1]], 
                       [[2, 0, 2], 
                        [0, 2, 0], 
                        [2, 0, 2]], 
                       ] 
                      ]) 
print('Filters:', filters.shape)

Filters: (3, 3, 3, 3)


In [59]:
def Conv2D(X, filters, stride=1, padding=0):
  n, c, h, w = X.shape
  n_f, c_f, h_f, w_f = filters.shape

  out_h = (h + padding * 2 - h_f) // stride + 1
  out_w = (w + padding * 2 - w_f) // stride + 1
  out = np.zeros([n, n_f, out_h, out_w])

  # padding
  if padding > 0:
    X_pad = np.zeros([n, c, h + padding * 2, w + padding * 2])
    X_pad[:, :, padding:padding*(-1), padding:padding*(-1)] = X
    # X_pad = np.pad(X, pad_width=padding, mode='constant', constant_values=0)  # 를 응용할 수도 있음
  else:
    X_pad = X

  for batch in range(n):  # 이미지 수 
    for channel in range(n_f):  # 채널
      for height in range(out_h): # 높이
        height_s = height * stride
        height_e = height_s + h_f

        for width in range(out_w):  # 너비
          width_s = width * stride
          width_e = width_s + w_f
          
          out[batch, channel, height, width] = np.sum(X_pad[batch, :, height_s:height_e, width_s:width_e] * filters[channel])

  return out

In [65]:
out = Conv2D(X, filters, stride=1, padding=1)
print(out.shape)
print(out)

(2, 3, 5, 5)
[[[[ 81. 121. 130. 110.  82.]
   [104. 174. 157. 191. 111.]
   [117. 158. 132. 153. 104.]
   [ 92. 130. 104. 122.  78.]
   [ 73.  81.  67.  63.  58.]]

  [[ 46. 132.  85. 158.  56.]
   [ 79. 197. 119. 244.  90.]
   [ 93. 159. 168. 186. 121.]
   [ 99. 165. 117. 159.  86.]
   [ 68.  87. 120.  84.  75.]]

  [[ 46. 132.  85. 158.  56.]
   [ 79. 197. 119. 244.  90.]
   [ 93. 159. 168. 186. 121.]
   [ 99. 165. 117. 159.  86.]
   [ 68.  87. 120.  84.  75.]]]


 [[[ 76. 124.  96. 123.  79.]
   [126. 168. 178. 171. 112.]
   [102. 161. 153. 164. 115.]
   [ 95. 153. 166. 185. 124.]
   [ 60.  87. 122. 118.  82.]]

  [[ 76. 133. 108. 110.  68.]
   [ 96. 188. 171. 178. 116.]
   [129. 189. 204. 167. 114.]
   [116. 168. 193. 200. 118.]
   [ 89. 100. 143.  88.  82.]]

  [[ 76. 133. 108. 110.  68.]
   [ 96. 188. 171. 178. 116.]
   [129. 189. 204. 167. 114.]
   [116. 168. 193. 200. 118.]
   [ 89. 100. 143.  88.  82.]]]]


In [66]:
out = Conv2D(X, filters, stride=2, padding=3)
print(out.shape)
print(out)

(2, 3, 5, 5)
[[[[  0.   0.   0.   0.   0.]
   [  0.  81. 130.  82.   0.]
   [  0. 117. 132. 104.   0.]
   [  0.  73.  67.  58.   0.]
   [  0.   0.   0.   0.   0.]]

  [[  0.   0.   0.   0.   0.]
   [  0.  46.  85.  56.   0.]
   [  0.  93. 168. 121.   0.]
   [  0.  68. 120.  75.   0.]
   [  0.   0.   0.   0.   0.]]

  [[  0.   0.   0.   0.   0.]
   [  0.  46.  85.  56.   0.]
   [  0.  93. 168. 121.   0.]
   [  0.  68. 120.  75.   0.]
   [  0.   0.   0.   0.   0.]]]


 [[[  0.   0.   0.   0.   0.]
   [  0.  76.  96.  79.   0.]
   [  0. 102. 153. 115.   0.]
   [  0.  60. 122.  82.   0.]
   [  0.   0.   0.   0.   0.]]

  [[  0.   0.   0.   0.   0.]
   [  0.  76. 108.  68.   0.]
   [  0. 129. 204. 114.   0.]
   [  0.  89. 143.  82.   0.]
   [  0.   0.   0.   0.   0.]]

  [[  0.   0.   0.   0.   0.]
   [  0.  76. 108.  68.   0.]
   [  0. 129. 204. 114.   0.]
   [  0.  89. 143.  82.   0.]
   [  0.   0.   0.   0.   0.]]]]
