XOR => NAND와 OR의 연산 결과에 AND를 씌워서 구해야 한다!


In [1]:
import numpy as np

In [11]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [211]:
class LogicGate:
  def __init__(self, input_data, target_data, lr):
    self.input_data = input_data.reshape(4, 2)
    self.target_data = target_data.reshape(4, 1)
    self.lr = lr

    self.W = np.random.randn(2, 1)
    self.b = np.random.rand(1)


  def loss_func(self):
    delta = 1e-5
    return -np.mean(self.target_data * np.log(self.O + delta) + (1 - self.target_data) * np.log(1 - self.O + delta))


  def train(self):
    n = target_data.shape[0]

    for step in range(8000):

      self.O = sigmoid(np.dot(self.input_data, self.W) + self.b)

      self.W -= np.dot(self.input_data.T, self.O - self.target_data) / n * self.lr
      self.b -= np.mean(self.O - self.target_data) * self.lr

      if step % 200 == 0:
        print('step: ', step, ', loss: ', self.loss_func())


  def predict(self, input_data):
    O = sigmoid(np.dot(input_data, self.W) + self.b)

    output_data = np.around(O) # 0.5 기준으로 반올림
    output_data = output_data.astype('int32')

    if len(output_data) == 1:
      return output_data[0]
    else:
      return output_data


In [212]:
# NAND

input_data = np.array([[0,0], [0,1], [1,0], [1,1]])
target_data = np.array([1, 1, 1, 0])

NAND_gate = LogicGate(input_data, target_data, 0.01)
NAND_gate.train()

step:  0 , loss:  0.8463327832854012
step:  200 , loss:  0.6737433484383224
step:  400 , loss:  0.5901405974279135
step:  600 , loss:  0.5374499473504563
step:  800 , loss:  0.4972942467031738
step:  1000 , loss:  0.46393017210947307
step:  1200 , loss:  0.43528113679797736
step:  1400 , loss:  0.4103456993737048
step:  1600 , loss:  0.3884750618500339
step:  1800 , loss:  0.3691725364144869
step:  2000 , loss:  0.3520339641624303
step:  2200 , loss:  0.33672507491803627
step:  2400 , loss:  0.3229686506466418
step:  2600 , loss:  0.31053482360772416
step:  2800 , loss:  0.2992329778226519
step:  3000 , loss:  0.28890489291526517
step:  3200 , loss:  0.2794189862593146
step:  3400 , loss:  0.2706655285661867
step:  3600 , loss:  0.2625527027084548
step:  3800 , loss:  0.25500337726945893
step:  4000 , loss:  0.247952475950019
step:  4200 , loss:  0.2413448378646533
step:  4400 , loss:  0.23513347890314001
step:  4600 , loss:  0.22927817892356223
step:  4800 , loss:  0.2237443326921859


In [213]:
NAND_gate.predict(np.array([[0,0], [1,1], [1,0], [0,1]]))

array([[1],
       [0],
       [1],
       [1]], dtype=int32)

In [214]:
# OR

input_data = np.array([[0,0], [0,1], [1,0], [1,1]])
target_data = np.array([0, 1, 1, 1])

OR_gate = LogicGate(input_data, target_data, 0.01)
OR_gate.train()

step:  0 , loss:  0.4691555182146002
step:  200 , loss:  0.4058054584533757
step:  400 , loss:  0.372047894071055
step:  600 , loss:  0.3480961796226333
step:  800 , loss:  0.32852719867727126
step:  1000 , loss:  0.3114888739195213
step:  1200 , loss:  0.29622043082980837
step:  1400 , loss:  0.2823463020438924
step:  1600 , loss:  0.2696438590173615
step:  1800 , loss:  0.25795895644681743
step:  2000 , loss:  0.24717272585004177
step:  2200 , loss:  0.23718748669956874
step:  2400 , loss:  0.2279201851324043
step:  2600 , loss:  0.21929894129901484
step:  2800 , loss:  0.211260954175229
step:  3000 , loss:  0.20375104899951238
step:  3200 , loss:  0.1967205666669793
step:  3400 , loss:  0.19012646297140054
step:  3600 , loss:  0.1839305551001557
step:  3800 , loss:  0.17809888192156298
step:  4000 , loss:  0.17260115722984598
step:  4200 , loss:  0.1674103010026536
step:  4400 , loss:  0.16250203686701736
step:  4600 , loss:  0.15785454596791493
step:  4800 , loss:  0.15344816892179

In [215]:
OR_gate.predict(np.array([[0,0],[1,1], [1,0], [0,1]]))

array([[0],
       [1],
       [1],
       [1]], dtype=int32)

In [216]:
# AND

input_data = np.array([[0,0], [0,1], [1,0], [1,1]])
target_data = np.array([0, 0, 0, 1])

AND_gate = LogicGate(input_data, target_data, 0.01)
AND_gate.train()

step:  0 , loss:  0.9120696151223849
step:  200 , loss:  0.7971451522972257
step:  400 , loss:  0.7179395329688583
step:  600 , loss:  0.6556229884890046
step:  800 , loss:  0.6036628291278574
step:  1000 , loss:  0.5593510574252687
step:  1200 , loss:  0.5211861495070014
step:  1400 , loss:  0.4881012696280685
step:  1600 , loss:  0.45924677456332474
step:  1800 , loss:  0.43392456735098184
step:  2000 , loss:  0.4115593890873847
step:  2200 , loss:  0.39167850941197885
step:  2400 , loss:  0.3738942354376634
step:  2600 , loss:  0.35788865206047105
step:  2800 , loss:  0.3434006486204358
step:  3000 , loss:  0.33021515016110536
step:  3200 , loss:  0.31815432456166726
step:  3400 , loss:  0.30707047618284744
step:  3600 , loss:  0.29684033606243443
step:  3800 , loss:  0.2873604871674815
step:  4000 , loss:  0.2785437017257769
step:  4200 , loss:  0.27031600655868293
step:  4400 , loss:  0.262614327402098
step:  4600 , loss:  0.2553845930364194
step:  4800 , loss:  0.2485802046043482

In [217]:
AND_gate.predict(np.array([[0,0], [1,1], [1,0], [0,1]]))

array([[0],
       [1],
       [0],
       [0]], dtype=int32)

In [219]:
# XOR

test_data = np.array([[0,1], [0,0], [1,1], [1,0]])

AND_input_data = np.zeros(test_data.shape)  # NAND와 OR 연산 결과를 저장

for idx in range(len(test_data)):
  data = test_data[idx]
  AND_input_data[idx] = [NAND_gate.predict(data), OR_gate.predict(data)]

print('Input\n', test_data)
print('\nOutput\n', AND_gate.predict(AND_input_data))

Input
 [[0 1]
 [0 0]
 [1 1]
 [1 0]]

Output
 [[1]
 [0]
 [0]
 [1]]
